### ISSUE TITLE
302 redirects gives error

### ISSUE THREAD

**Issue by ebrongers** [beamzer/ScirtScan#3]
When there is a URL with a redirect, the following error  occoured

tested with the URL www.landstede.nl whitch redirect to www.landstedembo.nl

**./scirtscan.py  websites.txt** 
Traceback (most recent call last):
  File "/home/..../PycharmProjects/ScirtScan/./scirtscan.py", line 371, in <module>
    header_check(website)
  File "/home/..../PycharmProjects/ScirtScan/./scirtscan.py", line 106, in header_check
    data = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by beamzer** [comment]
Thanks for reporting. One of the design criteria was to fail gracefully on errors, so I'll fix the crash on error ;)<br />

Looking into the example, it doesn't seem to be an error with redirection. The error occurs within the header_check function and shcheck.py happily follows HTTP redirections. You can see this for yourself with for instance:
> % curl -I https://surf.nl
HTTP/2 301
server: nginx
date: Sat, 25 Feb 2023 13:41:46 GMT
content-type: text/html; charset=iso-8859-1
x-frame-options: SAMEORIGIN
referrer-policy: origin
x-served-by: prod-ams
strict-transport-security: max-age=31536000;
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
location: https://www.surf.nl/

> % shcheck.py -j -d https://surf.nl
{"https://www.surf.nl/": {"present": {"X-XSS-Protection": "1;  etc...

The reason why www.landstede.nl gives an error, is because the certificate for the website is not valid for www.landstede.nl:
> % shcheck.py -j https://www.landstede.nl
SSL: Certificate validation error.
If you want to     ignore it run the program with the "-d" option.

The certificate for www.landstede.nl is for:
> *.landstedegroep.nl`

_(personally I consider wildcard certificates on top level domains a risk, if it gets compromised a hacker can pose as any website under that TLD)_ And it's also not in the list of Subject Alternative Names for the certificate:

`DNS Name: *.landstedegroep.nl|DNS Name: *.t-umbraco.landstedegroep.nl|DNS Name: *.p-umbraco.landstedegroep.nl|DNS Name: *.vechtdalcollege.nl|DNS Name: www.veiligheidsacademienwv.nl|DNS Name: www.thomasakempis.nl|DNS Name: www.agnietenzwartsluis.nl|DNS Name: www.groeiopleidingen.nl|DNS Name: www.agnietennieuwleusen.nl|DNS Name: www.meandercollege.nl|DNS Name: www.doc93.nl|DNS Name: www.orfeogymnasium.nl|DNS Name: www.hetccc.nl|DNS Name: www.agnietenwezep.nl|DNS Name: www.ichthusdronten.nl|DNS Name: www.morgencollege.nl|DNS Name: www.ichthuskampen.nl|DNS Name: www.jenaxl.nl|DNS Name: www.meanderbigband.nl|DNS Name: www.cse-zwolle.nl|DNS Name: www.talentstadpraktijkonderwijs.nl|DNS Name: www.talentstad.nl|DNS Name: www.internationalschoolzwolle.nl|DNS Name: www.landstedembo.nl|DNS Name: www.maatjeopmaat.nl|DNS Name: www.gerechtenland.nl|DNS Name: www.landstedesportcentrum.nl|DNS Name: www.start-college.nl|DNS Name: www.mensoaltingzwolle.nl|DNS
Name: www.kindeneducatie.nl|DNS Name: www.nieuwbouwichthuskampen.nl|DNS Name: www.zorgtrainingscentrum.nl
`

So I'll have the script output the certificate error and in this case it means skipping the other checks on that website since the websites just serves a 503 error and no redirect:
>  % curl -k -I https://www.landstede.nl
HTTP/1.1 503 Service Unavailable
Content-Length: 62
Connection: close
Cache-Control: no-cache,no-store
Pragma: no-cache
Server: DOS3.1

**Comment by beamzer** [comment]
Error handling is now improved and it doesn't crash anymore on shcheck when encountering an invalid certificate or an HTTP 5xx response.
